### ISSUE TITLE
Uniform eslint rules with codacy

### ISSUE THREAD

**Issue by gorankokin** [vmware/versatile-data-kit#1802] opened 2023-03-30 12:09 UTC
**What is the feature request? What problem does it solve?**
Uniform eslint rules with codacy if get codacy as a source of truth and best practices

**Suggested solution**
We should change some of the rules in eslint to align with the rules of codacy. Currently they diverged and contradict in some of the rules.

**Comment by ivakoleva** [comment] 2023-04-19 10:19
The description provided is very vague. Please add more details about the problem? What is an example diverging or contracting of rules you found? Please report the problem details @gorankokin

**Comment by sabadzhiev** [comment] 2023-07-28 12:23
Closing. Duplicate of: #1926.

**Closed by sabadzhiev** 2023-07-28 12:23 UTC
Labels: enhancement, area/frontend
