### ISSUE TITLE
vdk list -t "team" does not return newly added job

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#1238] opened 2022-10-13 13:49 UTC
**Describe the bug**
I am not sure what is happening . But when querying by team not all jobs are returned.  
It is reproducible by both API and CLI 

**Steps To Reproduce**
1. vdk create -n example-job -t test-team --cloud
2. vdk list -t test-team 
3. Job example-job should is not listed 

 **Expected behavior**
 Job example-job should be listed .... 

**Screenshots**

**Version  (please complete the following information):**
 - Control Service version: 1.5.657062384

 
 
**Additional context**
Add any other context about the problem here. Consider attaching logs if there are any.

**Comment by gageorgiev** [comment] 2023-01-30 08:32
Integration test relevant to this issue here - https://github.com/vmware/versatile-data-kit/pull/1385 - seems to not be able to reproduce the issue, or the issue is intermittent.

**Comment by tozka** [comment] 2023-01-30 09:06
Hi @gageorgiev , 

Thanks for looking into this. I tried to reproduce it as well based on the instructions and could not.

If we cannot reproduce it, then let's close it. 

If you have noticed any intermittent failures/issues, please post any findings (including upload details of logs/commands) here so if we re-open it in the future we have some information. Do post what kind of investigation you have done so far.

**Comment by gageorgiev** [comment] 2023-01-31 13:41
Attempted to reproduce manually by creating a job and listing all jobs, checking that the created job is there. Did this multiple times in a row.
Attempted to reproduce through an integration test which creates 100 jobs are lists them, checking that they all exist.

Either it is a rare issue, or it is no longer a problem. Closing this and closing the IT PR.

**Comment by tozka** [comment] 2023-01-31 15:06
changed the status to closed as not planned (cannot reproduce)

**Closed** 2023-03-03 12:29 UTC
Labels: bug, area/control-service
